name: WINDOWS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  windows-native:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Configure CMake
        shell: cmd
        run: cmake -H. -Bbuild -G "Visual Studio 16 2019" -T ClangCL -DCMAKE_BUILD_TYPE=MinSizeRel

      - name: Build
        shell: cmd
        run: cmake --build build --config MinSizeRel

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}